### ISSUE TITLE
Trouble Loading

### ISSUE THREAD

**Issue by Capticq** [DevLisuu/PrettyCapes-Fabric#4]
Hi! im having trouble running the 1.18.2 version of this mod using the curse-forge fabric loader along with Minecraftcapes, Fabric API, and Mod Menu mods, is there something wrong with the way im loading it? if not, any tips for how to fix this?
Thank you!
[edit] I've also tried this mod with the usual fabric loader and with different mods, and that didn't work

**Comment by LisuuDev** [comment]
I have no trouble launching with these mods installed, the issue must be somewhere on your side. Maybe try updating java if you still need help
![image](https://user-images.githubusercontent.com/68614968/176609273-016998e3-9add-4e62-affe-81d142bcfb58.png)

**Comment by LisuuDev** [comment]
Elytra Capes just seems not to affect capes while MinecraftCapes Mod is present. I'm going to try fixing it in 1.19 update.

**Comment by Capticq** [comment]
> Elytra Capes just seems not to affect capes while MinecraftCapes Mod is present. I'm going to try fixing it in 1.19 update.

Thanks a ton! That would mean the world to me

**Comment by LisuuDev** [comment]
I tried my best, but MinecraftCapes Mod does not provide any source code. I suggest downloading [Capes](https://modrinth.com/mod/capes) mod which supports every type of cape and is compatible with my mod.
