### ISSUE TITLE
ElytraCapes 2.2 for MC 1.19 to 1.19.2 only loads on 1.19.2

### ISSUE THREAD

**Issue by AleFunky** [DevLisuu/PrettyCapes-Fabric#5]
Curseforge and modrinth says that its for 1.19, 1.19.1 and 1.19.2, but the game wont load as it only accepts 1.19.2:
![imagen](https://user-images.githubusercontent.com/55950650/188124935-e597dbb5-ea8c-49e2-93a3-aeaa8696ac8a.png)

**Comment by LisuuDev** [comment]
Fixed 🗿
