### ISSUE TITLE
Elytra model is always on even when not wearing one

### ISSUE THREAD

**Issue by xnite7** [DevLisuu/PrettyCapes-Fabric#9]
problem: as the title says
version: 1.21 fabric
![image](https://github.com/user-attachments/assets/d435283e-3691-413a-ba26-30d2d813d4b6)

**Comment by xnite7** [comment]
wait im confused why did u make it check for dripleaf

**Comment by LisuuDev** [comment]
About the title, this is the point of the mod, and about your question I honestly don't remember why would that be, but probably it's something no one would wear in their chest slot so the code would never execute
